complete HW 25 september (AutoLayout)
ZalyalovIldar/HWLayoutsSwift pull request #1
Opened 2017-10-01 17:47 UTC by timbaev

2017-10-04 22:00 UTC, ZalyalovIldar requested changes
хорош, давай исправляй и like 👍

2017-10-04 22:00 UTC, ZalyalovIldar commented on VKProfile/Controllers/InfoTableViewController.swift
> +        self.tableView.rowHeight = UITableViewAutomaticDimension
без self :)

2017-10-04 22:00 UTC, ZalyalovIldar commented on VKProfile/Controllers/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(ViewController.rotated), name: NSNotification.Name.UIDeviceOrientationDidChange, object: nil)
подписавшись на нотификацию, нужно обязательно прописать отписываете от нотификаций при уничтожении контроллера
```swift 
deinit {
        NotificationCenter.default.removeObserver(self)
    }
```

2017-10-04 22:00 UTC, ZalyalovIldar commented on VKProfile/Controllers/ViewController.swift
> +        let indentation: CGFloat = 8
эту константу нужно вынести наружу и обозвать

2017-10-04 22:00 UTC, ZalyalovIldar commented on VKProfile/Controllers/ViewController.swift
> +        createBorders(to: menuButtons[1], on: .right)
лучше все таки называть в таком кейсе твои индексы, по которым ты достаешь объекты из массива с вьюхами, ну тип не понятно что за вьюха то, ну удалю я 1-юу или поменяю местами, и все сломается если ориентироваться просто на числа константные тут, так что давай выносить константу и обзывать, во всех остальных таких кейсах по коду тож поправь сразу)

2017-10-04 22:00 UTC, ZalyalovIldar commented on VKProfile/Controllers/ViewController.swift
> +        setTitle(with: infoButtons[6], count: user.files, declinationWord: DeclinationWordDictionary.file, attributes: attributes)
тут тоже тот же коммент насчет констант индексов

2017-10-04 22:00 UTC, ZalyalovIldar commented on VKProfile/Controllers/ViewController.swift
> +        let imageHeight: CGFloat = 97
константы все же выноси наверх, в методах такие константы оставлять лучше не нужно, все же все константы такого вида должны быть вместе наверху

2017-10-04 22:00 UTC, ZalyalovIldar commented on VKProfile/Controllers/ViewController.swift
> +        let textSize:CGFloat = 15
в константы за метод наверх к началу

2017-10-04 22:00 UTC, ZalyalovIldar commented on VKProfile/Controllers/ViewController.swift
>      private func createBorders(to view: UIView, on position: BorderPosition) {
вообще идея не плохая конечно, но в целом не очень, что называется "flexable", пока оставь, на паре объясню че почему лучше, пингани только

2017-10-04 22:00 UTC, ZalyalovIldar commented on VKProfile/Controllers/ViewController.swift
>          let noneMargin:CGFloat = 0
константы так же лучше наверх к началу класса убирать, и да, раз уж апеллируем модификаторами доступа, то и константы тогда делай fileprivate или private

2017-10-04 22:00 UTC, ZalyalovIldar commented on VKProfile/Controllers/ViewController.swift
> +        if (view is UIScrollView) {
без скобок можно

2017-10-04 22:00 UTC, ZalyalovIldar commented on VKProfile/Cells/PresentTableViewCell.swift
> +        accessoryButton = self.subviews.flatMap { $0 as? UIButton }.first
чет я этот момент пропустил что ли, напомни ка, зачем ты такую штуку мутишь?

2017-10-04 22:00 UTC, ZalyalovIldar commented on VKProfile/Controllers/InfoTableViewController.swift
> +        self.title = user.name
без "self" будет чище :)  (по коду убери где используешь вне блока)

2017-10-04 22:00 UTC, ZalyalovIldar commented on VKProfile/Controllers/InfoTableViewController.swift
> +    override func tableView(_ tableView: UITableView, estimatedHeightForRowAt indexPath: IndexPath) -> CGFloat {
корооче, раз уж ты замахнулся на 
```swift 
tableView.rowHeight = UITableViewAutomaticDimension
```
теперь тебе этот метод не нужен, вместо этого добавь во viewDidLoad эти 2 строчки 
```swift 
tableView.estimatedRowHeight = 50
tableView.estimatedSectionHeaderHeight = 50
```
И не забудь подчистить константы которые теперь не нужны

2017-10-05 20:47 UTC, timbaev commented on VKProfile/Cells/PresentTableViewCell.swift
> +        accessoryButton = self.subviews.flatMap { $0 as? UIButton }.first
Нет, не пропускали, было. Это для отображения стрелочки над подарками. Если делать через xib, то стрелочка всё равно стоит не там, где нужно. Пришлось оставить пока через код. На паре в пн покажу.

2017-10-15 12:48 UTC, closed without merging